#QuickLogic TCL Script
#Generated by Precision RTL Synthesis OEM Quicklogic 32-bit 2016.2.1.10 (Release Production Release, compiled Mon Jul 17 09:18:05 PDT 2017)
#Date: Thu Aug 27 13:56:52 2020

SetWorkDir "C:/Work/SVN/repos/hardware/trunk/FpgaIpDesigns/S3/USBserialport_S3B/rtl/project_1_impl_1/"
Load "C:/Work/SVN/repos/hardware/trunk/FpgaIpDesigns/S3/USBserialport_S3B/rtl/project_1_impl_1/AL4S3B_FPGA_top.edf"
SetOptionSess "Back Annotation" "Simulator" "Verilog"
RunAllTools
GenerateReport
Save
