#QuickLogic TCL Script
#Generated by Precision RTL Synthesis OEM Quicklogic 32-bit 2016.2.1.10 (Release Production Release, compiled Mon Jul 17 09:18:05 PDT 2017)
#Date: Fri Jun 18 21:42:26 2021

SetWorkDir "C:/Work/github/QuickLogic-Corp/s3-gateware/projects/S3_AEC/build_spde/project_1_impl_1/"
Load "C:/Work/github/QuickLogic-Corp/s3-gateware/projects/S3_AEC/build_spde/project_1_impl_1/top.edf"
SetOptionSess "Back Annotation" "Simulator" "Verilog"
RunAllTools
GenerateReport
Save
