dist: bionic
language: C
compiler: gcc
git:
  depth: 1

before_install:
  - export  INSTALL_DIR=~/symbiflow
  - SRC=https://github.com/QuickLogic-Corp/quicklogic-fpga-toolchain/releases/download/v1.2.0/Symbiflow_v1.2.0.gz.run
  - RUNFILE=$(basename $SRC)
  - echo "retrive new file"
  - wget $SRC
  - echo 'y' | bash $RUNFILE
  - export PATH="$INSTALL_DIR/install/bin:$INSTALL_DIR/install/bin/python:$PATH"
  - source "$INSTALL_DIR/conda/etc/profile.d/conda.sh"
  - conda activate

jobs:
  include:
    -name: "build"
    script:
      bash ci/makeall.csh
