`timescale 1ns/1ns

/************************************************************************
** File : r512x16_512x16.tf
** Design Date: April 11,2005
** Creation Date : Thu Jul 06 15:56:34 2017

** Created By SpDE Version : SpDE 2016.1.1 Release
** Author: QuickLogic Corporation,
** Copyright (C) 1998, Customers of QuickLogic may copy and modify this
** file for use in designing QuickLogic devices only.
** Description: This is a sample test fixture for your RAM bank.
** For each address, data is loaded in then read back
** The data is the address of the RAM location.
** The intended use of this file is to help users verify that the
** RAM Bank that is generated by SpDE is functionally correct.
************************************************************************/

module t;

integer i1,i2;

reg WClk,RClk,WD_SEL,RD_SEL;
reg WClk_En,RClk_En;
reg [1:0] WEN;
reg [8:0] WA;
reg [8:0] RA;
reg  [15:0] WD;
reg LS,DS,SD,LS_RB1,DS_RB1,SD_RB1;
wire [15:0] RD;

 r512x16_512x16 m(.WA(WA),.RA(RA),.WD(WD),.WClk(WClk),.RClk(RClk),.WClk_En(WClk_En),.RClk_En(RClk_En),.WD_SEL(WD_SEL),.RD_SEL(RD_SEL),.WEN(WEN),.RD(RD),.LS(LS),.DS(DS),.SD(SD),.LS_RB1(LS_RB1),.DS_RB1(DS_RB1),.SD_RB1(SD_RB1));

always
#10 WClk = ~WClk;
always
#10 RClk = ~RClk;

initial
begin
  WClk_En = 1;
  RClk_En = 1;
  WClk = 0;
  WD_SEL = 1;
WEN = 3 ;
  RClk = 0;
  RD_SEL = 0;
  i1 = 0;
  i2 = 0;
  repeat(512)
    begin
        WA = i1;
        WD = i2;
        #20 i1=i1+1; i2=i2+2;
    end
  i1 = 0;
  WD_SEL = 0;
  WEN = 0;
  RD_SEL = 1;
  repeat(512)
    begin
        RA = i1;
        #20 i1=i1+1;
    end
 $stop;
 $finish;
end

endmodule
